version: '3.9'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: xdebug-nginx
        ports:
            - "4444:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service

    # php
    php82-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: xdebug-php
        ports:
            - "4441:9000"
        volumes:
            - ./:/var/www/project
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini